apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-recommendation-pipeline
  labels:
    app: retail-recommendation-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-recommendation-pipeline
  template:
    metadata:
      labels:
        app: retail-recommendation-pipeline
    spec:
      containers:
        - name: retail-recommendation-pipeline
          image: chapelfob80930/retail-recommendation-pipeline:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always  # Correct location for imagePullPolicy
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: retail-recommendation-pipeline
spec:
  selector:
    app: retail-recommendation-pipeline
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
